name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  DOMAIN_NAME: ${{vars.DOMAIN_NAME}}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "TF_VAR_credentials={ access_key = \"${{secrets.AWS_ACCESS_KEY}}\", secret_key = \"${{secrets.AWS_SECRET_KEY}}\" }" >> $GITHUB_ENV
          echo "TF_VAR_rds={ database_identifier = \"${{secrets.DB_ID}}\", database_name = \"${{secrets.DB_NAME}}\", db_user = \"${{secrets.DB_USER}}\", db_pass = \"${{secrets.DB_PASS}}\" }" >> $GITHUB_ENV
          echo "TF_VAR_acm_certificate_domain_name = \"${{env.DOMAIN_NAME}}\"" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
